"use client";
import { useRef } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import "styles/styles.css";
import Container from "@mui/material/Container";
import Header from "components/header";
import { SnackbarProvider } from "notistack";
import { makeStore } from "store/store";
import { Provider } from "react-redux";
import { ThemeProvider } from "@mui/material/styles";
import theme from "styles/theme/theme";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const storeRef = useRef();
  if (!storeRef.current) {
    // Create the store instance the first time this renders
    storeRef.current = makeStore();
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={storeRef.current}>
          <ThemeProvider theme={theme}>
            <SnackbarProvider maxSnack={3} autoHideDuration={3000}>
              {children}
            </SnackbarProvider>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
